# Generated by Django 5.2.1 on 2025-11-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой'), ('prefer-not-to-say', 'Предпочитаю не говорить')], max_length=20, null=True),
        ),
    ]
