# Generated by Django 5.2.1 on 2025-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='num',
        ),
        migrations.AddField(
            model_name='form',
            name='operation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
