# Generated by Django 5.2.1 on 2025-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_remove_form_num_form_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
